using StaticArrays, ChargeFlipPhaser, SpaceGroups, LinearAlgebra, GLMakie

include(joinpath(@__DIR__, "..", "savers", "json_saver.jl"))

# Plane group pg, generated by a single glide reflection.
# Its linear part mirrors x -> -x, and it glides by half a cell along y,
# so in real space the symmetry sends a point (x, y) to (-x, y + 1/2).
# pg has no center of symmetry, so a general reflection and its antipode -k
# are NOT related by the group: the general orbits are of the complex type.
const G_pg = SpaceGroupQuotient([@SGE([-1 0; 0 1], [0//1, 1//2])])

# The asymmetric unit: three point atoms in general positions, with distinct
# weights, so the structure has no accidental symmetry beyond pg itself.
# Each entry is (fractional coordinate, scattering weight).
const BASE_ATOMS = [(SA[0.15, 0.10], 1.0), (SA[0.37, 0.62], 0.7), (SA[0.64, 0.31], 0.5)]

# Build the whole structure by applying every symmetry of pg to every base atom.
# This makes the density genuinely pg-symmetric, so its diffraction pattern has
# the correct glide extinctions and the intensities are consistent on each orbit.
function pg_atoms()
    atoms = Tuple{SVector{2,Float64},Float64}[]
    for (r, w) in BASE_ATOMS, g in G_pg
        push!(atoms, (mod.(g.a * r + g.b, 1.0), w))
    end
    atoms
end

# Structure factor of point atoms (no atomic surfaces: the atoms are pure points).
synthetic_amplitude(k::SVector{2,Int}, atoms) =
    sum(w * exp(2π * im * (k ⋅ r)) for (r, w) in atoms)

# Fill a DiffractionData with every reflection inside a resolution circle.
function generate_difdata(radius::Real)
    md = SMatrix{2,2,Float64}([1.0 0.0; 0.0 1.0]) # square cell, consistent with pg
    dd = DiffractionData(G_pg, md)
    atoms = pg_atoms()
    n = Int(floor(radius))
    for kx = 0:n, ky = -n:n
        (kx != 0 || ky > 0) || continue                  # take each Friedel pair once
        kx^2 + ky^2 < radius^2 || continue               # stay inside the resolution circle
        k = SVector{2,Int}(kx, ky)
        make_orbit(k, G_pg) isa ExtinctOrbit && continue # skip the glide extinctions
        f = synthetic_amplitude(k, atoms)
        add_peak!(dd, k, abs2(f))
    end
    dd
end

function example_monitor()
    dd = generate_difdata(20.0)

    # A phaser needs the intensities plus a regularizing form factor.
    formfactors = formfactors_synthetic(dd, ball_autocorr)
    phaser = Phaser(dd, formfactors)

    # Watch the density converge in a live window.
    pm = PhasingMonitor(phaser)
    s = Cut2D([1 0; 0 1], [0.0, 0.0], (512, 512)) # one unit cell
    add_panel!(pm, (1, 1), s, "pg synthetic structure", 1.0)
    Base.display(pm.fig)

    output = joinpath(@__DIR__, "results", "synthetic_pg.json")
    do_phasing!(phaser, hooks=MonitorHooks(pm),
        algorithm=SweepDown(fraction_flipped=0.7, decrement=0.99), saver=JSONSaver(output))
end

example_monitor()
